#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dconf-editor
Version  : 3.28.0
Release  : 1
URL      : https://download.gnome.org/sources/dconf-editor/3.28/dconf-editor-3.28.0.tar.xz
Source0  : https://download.gnome.org/sources/dconf-editor/3.28/dconf-editor-3.28.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: dconf-editor-bin
Requires: dconf-editor-data
Requires: dconf-editor-locales
Requires: dconf-editor-doc
BuildRequires : glib-dev
BuildRequires : libxml2-dev
BuildRequires : meson
BuildRequires : ninja
BuildRequires : pkgconfig(dconf)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : python3
BuildRequires : vala

%description
This is dconf-editor.  It used to be part of the 'dconf' package.

%package bin
Summary: bin components for the dconf-editor package.
Group: Binaries
Requires: dconf-editor-data

%description bin
bin components for the dconf-editor package.


%package data
Summary: data components for the dconf-editor package.
Group: Data

%description data
data components for the dconf-editor package.


%package doc
Summary: doc components for the dconf-editor package.
Group: Documentation

%description doc
doc components for the dconf-editor package.


%package locales
Summary: locales components for the dconf-editor package.
Group: Default

%description locales
locales components for the dconf-editor package.


%prep
%setup -q -n dconf-editor-3.28.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1526672678
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir

%install
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang dconf-editor

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dconf-editor

%files data
%defattr(-,root,root,-)
/usr/share/applications/ca.desrt.dconf-editor.desktop
/usr/share/bash-completion/completions/dconf-editor
/usr/share/dbus-1/services/ca.desrt.dconf-editor.service
/usr/share/glib-2.0/schemas/ca.desrt.dconf-editor.gschema.xml
/usr/share/icons/hicolor/16x16/apps/ca.desrt.dconf-editor.png
/usr/share/icons/hicolor/22x22/apps/ca.desrt.dconf-editor.png
/usr/share/icons/hicolor/24x24/apps/ca.desrt.dconf-editor.png
/usr/share/icons/hicolor/256x256/apps/ca.desrt.dconf-editor.png
/usr/share/icons/hicolor/32x32/apps/ca.desrt.dconf-editor.png
/usr/share/icons/hicolor/48x48/apps/ca.desrt.dconf-editor.png
/usr/share/icons/hicolor/64x64/apps/ca.desrt.dconf-editor.png
/usr/share/icons/hicolor/scalable/apps/ca.desrt.dconf-editor-symbolic.svg
/usr/share/metainfo/ca.desrt.dconf-editor.appdata.xml

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files locales -f dconf-editor.lang
%defattr(-,root,root,-)

